#!/bin/sh

FILE=$(zzzfoo --synthetic-abstract)

if [ -z $FILE ]; then
	exit
fi

MIMETYPE=$(xdg-mime query filetype "$FILE")
MIMEAPP=$(xdg-mime query default "$MIMETYPE")

if [ -z $MIMEAPP ] || [ $MIMEAPP = "nvim.desktop" ]; then
	alacritty -e sh -c "nvim '${FILE}'"
else
	xdg-open "$FILE"
fi

