#!/bin/bash

# https://github.com/iambecomeroot/dotfiles/blob/master/bin/bin/lock

rectangles=" "

SR=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]*x[0-9][0-9]*[^ ]*')
for RES in $SR; do
	SRA=(${RES//[x+]/ })
	CX=$((${SRA[2]} + 25))
	CY=$((${SRA[1]} - 80))
	rectangles+="rectangle $CX,$CY $((CX+300)),$((CY-80)) "
done

tmpbg=/tmp/screen.png
scrot $tmpbg
convert $tmpbg -scale 10% -scale 1000% \
	-draw "fill black fill-opacity 0.4 $rectangles" $tmpbg

i3lock \
	-i $tmpbg \
	--timepos="x-90:h-ch-20" \
	--datepos="tx+24:ty+25" \
	--clock --datestr "Type password to unlock..." \
	--insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
	--keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
	--insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
	--ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+290:h-120" \
	--radius=20 --ring-width=3 --veriftext="" --wrongtext="" \
	--textcolor="ffffffff" --timecolor="ffffffff" --datecolor="ffffffff"

rm $tmpbg

