#!/usr/bin/env bash

# rofi-power
# Use rofi to call systemctl for shutdown, reboot, etc

# 2016 Oliver Kraitschy - http://okraits.de

# Modified from https://github.com/okraits/rofi-tools/blob/master/rofi-power

options() {
	echo "  Exit window manager"
	echo "  Reboot system"
	echo "  Power-off system"
	echo "  Suspend system"
	echo "  Hibernate system"
}

# source configuration or use default values
if [ -f $HOME/.config/rofi-power/config ]; then
  source $HOME/.config/rofi-power/config
else
  LAUNCHER="rofi -width 30 -lines 5 -dmenu -i -p rofi-power"
  USE_LOCKER="true"
  LOCKER="i3lock"
  EXIT="i3-msg exit"
fi

option=`echo -e "$(options)" | $LAUNCHER | awk '{print $1}' | tr -d '\r\n'`
if [ ${#option} -gt 0 ]
then
    case $option in
      Exit)
        $EXIT
        ;;
      Reboot)
        systemctl reboot
        ;;
      Power-off)
        systemctl poweroff
        ;;
      Suspend)
        $($USE_LOCKER) && "$LOCKER"; systemctl suspend
        ;;
      Hibernate)
        $($USE_LOCKER) && "$LOCKER"; systemctl hibernate
        ;;
      *)
        ;;
    esac
fi

