#!/usr/bin/env bash

readonly argv0="$0"
readonly url='http://myexternalip.com/raw'
declare -i full=0

usage() {
    echo "usage: $argv0 [-f]"
    exit 1
}

while getopts f OPT; do
    case $OPT in
        f) full=1 ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ((full)); then
    echo "SSID:      $(nmcli device wifi list | grep \* | awk '{printf $2}')"
    echo "Interface: $(ip route get 1.2.3.4 | awk '{print $5}')"
    echo "Internal:  $(ip route get 1.2.3.4 | awk '{print $7}')"
    echo "External:  $(curl -s "$url")"
else
    echo "SSID:      $(nmcli device wifi list | grep \* | awk '{printf $2}')"
    echo "Interface: $(ip route get 1.2.3.4 | awk '{print $7}')"
fi
