#!/bin/sh
devmon --no-gui --exec-on-drive "notify-send --icon=block-device --urgency=low \"Volume %l has been mounted to \\\"%d\\\"\"" --exec-on-unmount "notify-send --icon=block-device --urgency=low \"Volume %l has been unmounted\""

