#!/bin/bash

TEXTBOOKS="$TEXTBOOKS  ~/Downloads/Textbooks/Unit 3 & 4/Methods Cambridge VCE U3&4.pdf"
TEXTBOOKS="$TEXTBOOKS\n~/Downloads/Textbooks/Unit 3 & 4/Specialist Cambridge VCE U3&4.pdf"
TEXTBOOKS="$TEXTBOOKS\n~/Downloads/Textbooks/Unit 3 & 4/Physics Heinemann VCE U3&4.pdf"
TEXTBOOKS="$TEXTBOOKS\n~/Downloads/SPESH WORKED SOLUTIONS"

FILE=$(echo -e $TEXTBOOKS | rofi -i -dmenu -p textbooks)

if [ -z "$FILE" ]; then
	exit
fi

FILE=$HOME"/"${FILE#"~/"}
MIMETYPE=$(xdg-mime query filetype "$FILE")

if [ "$MIMETYPE" = "inode/directory" ]; then
	alacritty -e ranger "$FILE"
else
	xdg-open "$FILE"
fi
