#!/bin/bash
if [ -d "/opt/vivaldi" ]; then
	sudo ln -s /home/christopher/.cache/wal/colors.css /opt/vivaldi/resources/vivaldi/style/colors.css
fi

if [ -d "/opt/vivaldi-snapshot" ]; then
	sudo ln -s /home/christopher/.cache/wal/colors.css /opt/vivaldi-snapshot/resources/vivaldi/style/colors.css
fi
